#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend eslamalx.tech
        bind *:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 432595-web-01 54.197.21.242:80
        server 432595-web-02 34.239.107.56:80
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
